

FlowField f;
Vehicle v;

void setup() {
  size (1200, 900);
  //surface.setResizable(true);
  //fullScreen();
  f = new FlowField(15);
  
  
 
  //surface.setSize(f.p.width, f.p.height);
  f.display(); // display the flow field

  // put the vehicle in the middle
  v = new Vehicle(width/2, height/2);
}


void draw() {
  v.follow(f); // Apply the steering force to follow the flow field
  v.update(); // Update the velocity and location, based on the acceleration generated by the steering force
  //v.display(); // display the vehicle
}
