
ArrayList<ArrayList<PVector>> arrFields; //create an array list to store vectors from flow field in order to do some "cool" animation later
FlowField f;
//Vehicle v;
int count;
ArrayList<Boid> boids;  //arraylist to store vehicles

Flock flock;

void setup() {
  size (1000, 700);
  background(10, 150, 150);
  f = new FlowField(15);
  flock = new Flock();
  boids = new ArrayList<Boid>();
  count = 0;
  arrFields = f.fields;
  //f.aDisplay();
  //f.display();
   //f.cDisplay();



  // put the vehicle in the middle
  //v = new Vehicle(width/2, height/2);
}


void draw() {
  background(10, 150, 150);
  //if (count > arrFields.size() - 1){
  //  count = 0;
  //  background(10,150,150);
  //}else{
  //  f.bDisplay(arrFields.get(count), count);
  //  count++;

  //}
  //delay(200);
  //stroke(200, 70, 150);
  //f.aDisplay();
  //f.display();
  f.mouseFlowField();
  f.display();
  
  //go through vehicles and check if the current vehcile is still in the field; if in, display else remove
  //for (Boid b : boids) {
  //  if (b.location.x > width || b.location.x < 0 || b.location.y > height || b.location.y < 0){
  //    boids.remove(b);
  //  }else{
  //    //b.follow(f); // Apply the steering force to follow the flow field
  //    b.update(); // Update the velocity and location, based on the acceleration generated by the steering force
  //    b.display(); // display the vehicle
  //  }
  //}
  //f.aDisplay(); // display the flow field
  
  flock.run();
}

void mousePressed() {
  flock.addBoid(new Boid(mouseX, mouseY)); //when mouse is pressed, create a vehicle at the mouse's location
}
